# Generated by Django 4.2.3 on 2023-08-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Models", "0002_files"),
    ]

    operations = [
        migrations.RenameField(
            model_name="files",
            old_name="phone",
            new_name="model_name",
        ),
        migrations.AddField(
            model_name="model",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="files"),
        ),
        migrations.AlterField(
            model_name="model",
            name="publish_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
