# Generated by Django 4.2.3 on 2023-08-12 10:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Models", "0003_rename_phone_files_model_name_model_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model",
            name="file",
        ),
        migrations.AlterField(
            model_name="model",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
