# Generated by Django 4.2.3 on 2023-08-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Models", "0004_remove_model_file_alter_model_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Reject", "Reject"),
                    ("Aprove", "Aprove"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
