# Generated by Django 4.2.3 on 2023-08-15 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Models", "0006_category_parent_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent_category",
        ),
        migrations.CreateModel(
            name="Sub_Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Models.category",
                    ),
                ),
            ],
        ),
    ]
