# Generated by Django 4.2.3 on 2023-08-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Models", "0007_remove_category_parent_category_sub_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="sub_category",
            field=models.ForeignKey(
                default="text to audio",
                on_delete=django.db.models.deletion.CASCADE,
                to="Models.sub_category",
            ),
            preserve_default=False,
        ),
    ]
