# Generated by Django 4.2.3 on 2023-08-15 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Models", "0008_model_sub_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Models.sub_category",
            ),
        ),
    ]
