# Generated by Django 4.2.3 on 2023-07-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Login", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="first_address",
            new_name="address",
        ),
        migrations.AddField(
            model_name="profile",
            name="github",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
