# Generated by Django 4.2.3 on 2023-07-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Login", "0003_user_address_user_full_name_user_github_user_phone_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="university_name",
            new_name="university",
        ),
    ]
