# Generated by Django 4.2.3 on 2023-07-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Login", "0004_rename_university_name_user_university"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Transgender", "Transgender"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
