# Generated by Django 4.2.3 on 2023-07-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Login", "0005_user_country_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
