# Generated by Django 4.2.3 on 2023-07-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("Login", "0006_user_birth_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Custom_User",
        ),
    ]
