# Generated by Django 4.2.3 on 2023-07-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Login", "0008_rename_custom_user_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
