# Generated by Django 4.2.3 on 2023-07-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Login", "0010_user_verification_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="verification_token_expiration",
        ),
    ]
