# Generated by Django 4.2.3 on 2023-07-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Login", "0011_remove_user_verification_token_expiration"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verify",
            field=models.BooleanField(default=False),
        ),
    ]
