# Generated by Django 4.2.3 on 2023-08-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Login", "0013_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Visitor", "Visitor"),
                    ("Member", "Member"),
                    ("Premium Member", "Premium Member"),
                ],
                default="Visitor",
                max_length=50,
            ),
        ),
    ]
